# Enable trace level reconfiguration function
# Must be present before any TRC_ trace level settings
TraceConf=true

# Trace level configuration
#   BT_TRACE_LEVEL_NONE    0    ( No trace messages to be generated )
#   BT_TRACE_LEVEL_ERROR   1    ( Error condition trace messages )
#   BT_TRACE_LEVEL_WARNING 2    ( Warning condition trace messages )
#   BT_TRACE_LEVEL_API     3    ( API traces )
#   BT_TRACE_LEVEL_EVENT   4    ( Debug messages for events )
#   BT_TRACE_LEVEL_DEBUG   5    ( Full debug messages )
#   BT_TRACE_LEVEL_VERBOSE 6    ( Verbose messages ) - Currently supported for TRC_BTAPP only.
TRC_BTM=2
TRC_HCI=2
TRC_L2CAP=2
TRC_RFCOMM=2
TRC_OBEX=2
TRC_AVCT=2
TRC_AVDT=2
TRC_AVRC=2
TRC_AVDT_SCB=2
TRC_AVDT_CCB=2
TRC_A2D=2
TRC_SDP=2
TRC_SMP=2
TRC_BTAPP=2
TRC_BTIF=2
TRC_BNEP=2
TRC_PAN=2
TRC_HID_HOST=2
TRC_HID_DEV=2

# This is Log configuration for new C++ code using LOG() macros.
# See libchrome/base/logging.h for description on how to configure your logs.
# sample configuration:
#LoggingV=--v=0
#LoggingVModule=--vmodule=*/btm/*=1,btm_ble_multi*=2,btif_*=1

# PTS testing helpers

# Secure connections only mode.
# PTS_SecurePairOnly=true

# Disable LE Connection updates
#PTS_DisableConnUpdates=true

# Disable BR/EDR discovery after LE pairing to avoid cross key derivation errors
#PTS_DisableSDPOnLEPair=true

# SMP Pair options (formatted as hex bytes) auth, io, ikey, rkey, ksize
#PTS_SmpOptions=0xD,0x4,0xf,0xf,0x10

# PTS AVRCP Test mode
#PTS_AvrcpTest=true

# SMP Certification Failure Cases
# Set any of the following SMP error values (from smp_api_types.h)
# to induce pairing failues for various PTS SMP test cases.
# Setting PTS_SmpFailureCase to 0 means normal operation.
# Failure modes:
#
#  SMP_PASSKEY_ENTRY_FAIL = 1
#  SMP_PAIR_AUTH_FAIL = 3
#  SMP_CONFIRM_VALUE_ERR = 4
#  SMP_PAIR_NOT_SUPPORT = 5
#  SMP_PAIR_FAIL_UNKNOWN = 8
#  SMP_REPEATED_ATTEMPTS = 9
#  SMP_NUMERIC_COMPAR_FAIL = 12
#PTS_SmpFailureCase=0

# LPM Local configuration
# 1st Param is wake_mode i.e 0 - Transport sleep, 1 - OOB wake
# 2nd Param is WakeupFilteringFlags i.e BIT(0) - Whitelist, BIT(1) - ADV Data Pattern,
#    BIT(2) - Accept connection from Directed advertising, BIT(3) - undirected advertising
# 3rd Param is WakeSources i.e BIT(0) - BLE Scan, BIT(1) - BLE Advertise, BIT(2) - Page Scan
#    BIT(3) - HID, BIT(4) - HOGP, BIT(5) - FMP, BIT(2) - PXP
# 4th Param is Delay to Sleep in Micro Seconds
#LMP_WAKEUP_CONFIG=0x00,0x01,0xF00C,0x0000
# Configuration for HID
#LMP_WAKEUP_CONFIG=0x00,0x01,0x0C,0x00F0
#CONFIGURATION FOR HOGP - BLE SCAN, HOGP
LMP_WAKEUP_CONFIG=0x01,0x01,0x22,0x00F0,00:00:00:00:00:00,0x0384,0x00,0x00
#CONFIGURATION FOR HOGP - BLE SCAN
#LMP_WAKEUP_CONFIG=0x00,0x01,0x01,0x00F0

#LPM Page scan Params
# 1st Param is page_scan_interaval Eg:0x0800 meaning 1.28s i.e 0.225*2048
# Eg:0x0010 meaning 10ms i.e 12x0.225ms
# 2nd Param is page_scan_window Eg:0x0024 meaning 22.5ms i.e 0.225*32
# Eg:0x0010 meaning 10ms i.e 12x0.225ms
LPM_PAGE_SCAN_PARAMS=0x0012,0x0012

#LPM BLE SCAN PARAMS
#1st param is BLE SCAN TYPE
#2nd param is BLE scan interaval Eg:0x0010 meaning 10ms i.e 12x0.225ms
#3rd Param is BLE scan window Eg:0x0010 meaning 10ms i.e 12x0.225ms
#4th Param is BLE Scan filter policy
#LPM_BLE_SCAN_PARAMS=0x0012,0x0012,0x01,0x01
LPM_BLE_SCAN_PARAMS=0x0012,0x0012,0x01,0x01
