/*
 * Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause-Clear.
 */
#define BT_DM_EVT_START 0x0000
#define BT_DM_EVT_MAX 0x0DFF
#define BT_SDP_EVT_START 0x0E00
#define BT_SDP_EVT_MAX 0x0EFF
#define BT_RFCOMM_EVT_START 0x0F00
#define BT_RFCOMM_EVT_MAX 0x0FFF
#define BT_GATT_EVT_START 0x1000
#define BT_GATT_EVT_MAX 0x1FFF
#define BT_AV_EVT_START 0x2000
#define BT_AV_EVT_MAX 0x2FFF
#define BT_AVRCP_EVT_START 0x3000
#define BT_AVRCP_EVT_MAX 0x3FFF
#define BT_HFP_EVT_START 0x4000
#define BT_HFP_EVT_MAX 0x4FFF
#define BT_HFAG_EVT_START 0x5000
#define BT_HFAG_EVT_MAX 0x5FFF

enum decode_type {
   PROTO_ENC_DEC,
   PROTO_RAW_BYTES,
   PROTO_NONE,
};

#define MAX_LENGTH_WITH_PROTO_NONE 6
// Keep adding all profiles matching range
#define PAYLOAD_LENGTH_WITH_PROTO_NONE 0

enum bluetooth_dm {
	BT_DM_ENABLE = BT_DM_EVT_START, /*enable*/
	BT_DM_DISABLE,
	BT_DM_CLEANUP,
	BT_DM_GET_ADAPTER_PROPERTIES,
	BT_DM_GET_ADAPTER_PROPERTY,
	BT_DM_GET_ADAPTER_PROPERTY_NAME,
	BT_DM_SET_ADAPTER_PROPERTY,
	BT_DM_GET_REMOTE_DEVICE_PROPERTIES,
	BT_DM_GET_REMOTE_DEVICE_PROPERTY_BY_TYPE,
	BT_DM_SET_REMOTE_DEVICE_PROPERTIES,
	BT_DM_GET_REMOTE_SRV_RECORD,
	BT_DM_GET_REMOTE_SERVICES,
	BT_DM_START_DISCOVERY,
	BT_DM_CANCEL_DISCOVERY,
	BT_DM_CREATE_BOND,
	BT_DM_CREATE_BOND_OOB,
	BT_DM_REMOVE_BOND,
	BT_DM_CANCEL_BOND,
	BT_DM_GET_CONNECTION_STATE,
	BT_DM_PIN_REPLY,
	BT_DM_SSP_REPLY,
	BT_DM_ADAPTER_STATE_CHANGE_CB,
	BT_DM_ADAPTER_PROPERTIES_CB,
	BT_DM_REMOTE_DEVICE_PROPERTIES_CB,
	BT_DM_DISCOVERY_STATE_CHANGE_CB,
	BT_DM_DEVICE_FOUND_CB,
	BT_DM_PIN_REQUEST_CB,
	BT_DM_SSP_REQUEST_CB,
	BT_DM_BOND_STATE_CHANGE_CB,
	BT_DM_ACL_STATE_CHANGE_CB,
	BT_DM_LE_ADAPTER_PROPERTIES_CB,
  BT_DM_SSR_CB,


	BT_DM_API_MAX = BT_DM_EVT_MAX,
};

enum bluetooth_rfcomm {
	BT_RFCOMM_CREATE_SOCKET = BT_RFCOMM_EVT_START, /*enable*/
	BT_RFCOMM_CONNECT_SOCKET,
	BT_RFCOMM_WRITE_SOCKET_DATA,
	BT_RFCOMM_SCN_CB,
	BT_RFCOMM_SRV_OPEN_CB,
	BT_RFCOMM_CLIENT_CONNECT_CB,
	BT_RFCOMM_SOCKET_DATA_CB,
    BT_RFCOMM_DISCONNECT_SOCKET,
	BT_RFCOMM_DISCONNECT_SOCKET_CB,
	BT_RFCOMM_CLOSE_SERVER,

	BT_RFCOMM_API_MAX = BT_RFCOMM_EVT_MAX,
};

enum bluetooth_sdp {
        BT_SDP_SEARCH = BT_SDP_EVT_START,
        BT_SDP_SEARCH_COMPLETE_CB,

        BT_SDP_API_MAX = BT_SDP_EVT_MAX,
};

enum bluetooth_hf_client {
  BT_HF_CLIENT_INIT = BT_HFP_EVT_START,
  BT_HF_CLIENT_CONNECT,
  BT_HF_CLIENT_DISCONNECT,
  BT_HF_CLIENT_CONNECT_AUDIO,
  BT_HF_CLIENT_DISCONNECT_AUDIO,
  BT_HF_CLIENT_START_VOICE_RECOGNITION,
  BT_HF_CLIENT_STOP_VOICE_RECOGNITION,
  BT_HF_CLIENT_VOLUME_CONTROL,
  BT_HF_CLIENT_DIAL_NUM,
  BT_HF_CLIENT_DIAL_MEMORY,
  BT_HF_CLIENT_CALL_HANDLE,
  BT_HF_CLIENT_QUERY_CURRENT_CALLS,
  BT_HF_CLIENT_QUERY_CURRENT_OPERATOR,
  BT_HF_CLIENT_RETRIVE_SUBSCRIBER_INFO,
  BT_HF_CLIENT_SEND_DTMF_CODE,
  BT_HF_CLIENT_GET_VOICETAG_NUM,
  BT_HF_CLIENT_DEINIT,
  BT_HF_CLIENT_SEND_AT_CMD,

  /* Call backs */
  BT_HF_CLIENT_CONN_STATE_CB,
  BT_HF_CLIENT_AUDIO_STATE_CB,
  BT_HF_CLIENT_VOICE_RECOGNITION_CB,
  BT_HF_CLIENT_NETWORK_STATE_CB,
  BT_HF_CLIENT_NETWORK_ROAM_CB,
  BT_HF_CLIENT_NETWORK_SIGNAL_CB,
  BT_HF_CLIENT_BATTERY_LEVEL_CB,
  BT_HF_CLIENT_CURRENT_OPERATOR_CB,
  BT_HF_CLIENT_CALL_CB,
  BT_HF_CLIENT_CALLSETUP_CB,
  BT_HF_CLIENT_CALLHELD_CB,
  BT_HF_CLIENT_RESP_HOLD_CB,
  BT_HF_CLIENT_CLIP_CB,
  BT_HF_CLIENT_CALL_WAITING_CB,
  BT_HF_CLIENT_CURRENT_CALLS_CB,
  BT_HF_CLIENT_VOLUME_CHANGE_CB,
  BT_HF_CLIENT_CMD_COMPLETE_CB,
  BT_HF_CLIENT_SUBSCRIBER_INFO_CB,
  BT_HF_CLIENT_INBAND_RINGTONE_CB,
  BT_HF_CLIENT_LAST_VOICE_TAG_NUM_CB,
  BT_HF_CLIENT_RING_IND_CB,
  BT_HF_CLIENT_UNKNOWN_EVT_CB = BT_HFP_EVT_MAX,

};

enum bluetooth_hf {
  BT_HF_INIT = BT_HFAG_EVT_START, /*init*/
  BT_HF_CONNECT,
  BT_HF_DISCONNECT,
  BT_HF_CONNECT_AUDIO,
  BT_HF_DISCONNECT_AUDIO,
  BT_HF_IS_NOISE_REDUCTION_SUPPORTED,
  BT_HF_IS_VOICE_RECOGNITION_SUPPORTED,
  BT_HF_START_VOICE_RECOGNITION,
  BT_HF_STOP_VOICE_RECOGNITION,
  BT_HF_VOLUME_CONTROL,
  BT_HF_DEVICE_STATUS_NOTFICATION,
  BT_HF_COPS_RESPONSE,
  BT_HF_CIND_RESPONSE,
  BT_HF_FORMATTED_AT_RESPONSE,
  BT_HF_AT_RESPONSE,
  BT_HF_CLCC_RESPONSE,
  BT_HF_PHONE_STATE_CHANGE,
  BT_HF_CLEANUP,
  BT_HF_SET_SCO_ALLOWED,
  BT_HF_SEND_BSIR,
  BT_HF_SET_ACTIVE_DEVICE,
  /* callbacks */
  BT_HF_CONN_STATE_CB,
  BT_HF_AUDIO_STATE_CB,
  BT_HF_VOICE_RECOGNITION_CB,
  BT_HF_ANSWER_CALL_CB,
  BT_HF_HANGUP_CALL_CB,
  BT_HF_VOL_CONTROL_CB,
  BT_HF_DIAL_CALL_CB,
  BT_HF_DTMF_CMD_CB,
  BT_HF_NOISE_REDUCTION_CB,
  BT_HF_WBS_CB,
  BT_HF_AT_CHLD_CB,
  BT_HF_AT_CNUM_CB,
  BT_HF_AT_CIND_CB,
  BT_HF_AT_COPS_CB,
  BT_HF_AT_CLCC_CB,
  BT_HF_UNKNOWN_AT_CB,
  BT_HF_KEY_PRESSED_CB,
  BT_HF_AT_BIND_CB,
  BT_HF_AT_BIEV_CB,
  BT_HF_AT_BIA_CB,
  BT_HF_PEER_FEAT_CB,
  BT_HF_API_MAX = BT_HFAG_EVT_MAX,
};

enum bluetooth_a2dp {
  BT_AV_INIT = BT_AV_EVT_START,
  BT_AV_CONNECT,
  BT_AV_DISCONNECT,
  BT_AV_START_STREAM,
  BT_AV_STOP_STREAM,
  BT_AV_ACTIVE,
  BT_AV_SILENCE,
  BT_AV_CODEC_CONFIG,
  BT_AV_CLEANUP,

    /* callbacks */
  BT_AV_CONN_STATE_CB,
  BT_AV_AUDIO_STATE_CB,
  BT_AV_SRC_CODEC_CONFIG_CB,
  BT_AV_DELAY_REPORT_CB,

  BT_AV_API_MAX = BT_AV_EVT_MAX
};

enum bluetooth_avrcp_tg {
  BT_AVRC_INIT = BT_AVRCP_EVT_START,
  BT_AVRC_GET_PLAY_STATUS_RSP,
  BT_AVRC_LIST_PLAYER_APP_ATTR_RSP,
  BT_AVRC_LIST_PLAYER_APP_VALUE_RSP,
  BT_AVRC_GET_PLAYER_APP_VALUE_RSP,
  BT_AVRC_SET_PLAYER_APP_VALUE_RSP,
  BT_AVRC_GET_PLAYER_APP_ATTR_TEXT_RSP,
  BT_AVRC_GET_PLAYER_APP_VALUE_TEXT_RSP,
  BT_AVRC_GET_ELEMENT_ATTR_RSP,
  BT_AVRC_REGISTER_NOTIFICATION_RSP,
  BT_AVRC_GET_FOLDER_ITEMS_LIST,
  BT_AVRC_SET_ADDRESSED_PLAYER,
  BT_AVRC_SET_BROWSED_PLAYER_RSP,
  BT_AVRC_CHANGE_PATH_RSP,
  BT_AVRC_SEARCH_RSP,
  BT_AVRC_GET_ITEM_ATTR_RSP,
  BT_AVRC_ADD_TO_NOW_PLAYING_RSP,
  BT_AVRC_PLAY_ITEM_RSP,
  BT_AVRC_GET_TOTAL_NUM_OF_ITEMS_RSP,
  BT_AVRC_SET_VOLUME,
  BT_AVRC_UPDATE_PLAY_STATUS_TO_STACK,
  BT_AVRC_IS_DEVICE_ACTIVE_IN_HANDOFF,
  BT_AVRC_CLEANUP,

  // Callbacks

  BT_AVRC_REMOTE_FEATURES_CB,
  BT_AVRC_GET_PLAY_STATUS_CB,
  BT_AVRC_LIST_PLAYER_APP_ATTR_CB,
  BT_AVRC_LIST_PLAYER_APP_VALUES_CB,
  BT_AVRC_GET_PLAYER_APP_VALUE_CB,
  BT_AVRC_GET_PLAYER_APP_ATTRS_TEXT_CB,
  BT_AVRC_GET_PLAYER_APP_VALUES_TEXT_CB,
  BT_AVRC_SET_PLAYER_APP_VALUE_CB,
  BT_AVRC_GET_ELEMENT_ATTR_CB,
  BT_AVRC_REGISTER_NOTIFICATION_CB,
  BT_AVRC_VOLUME_CHANGE_CB,
  BT_AVRC_PASSTHROUGH_CMD_CB,
  BT_AVRC_SET_ADDRESSED_PLAYER_CB,
  BT_AVRC_SET_BROWSED_PLAYER_CB,
  BT_AVRC_GET_FOLDER_ITEMS_CB,
  BT_AVRC_CHANGE_PATH_CB,
  BT_AVRC_GET_ITEM_ATTR_CB,
  BT_AVRC_PLAY_ITEM_CB,
  BT_AVRC_GET_TOTAL_NUM_OF_ITEMS_CB,
  BT_AVRC_SEARCH_CB,
  BT_AVRC_ADD_TO_NOW_PLAYING_CB,
  BT_AVRC_CONNECTION_STATE_CB = BT_AVRCP_EVT_MAX,
};
