/*
 * Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause-Clear.
 */
#define BT_DM_EVT_START 0x0000
#define BT_DM_EVT_MAX 0x0DFF
#define BT_SDP_EVT_START 0x0E00
#define BT_SDP_EVT_MAX 0x0EFF
#define BT_RFCOMM_EVT_START 0x0F00
#define BT_RFCOMM_EVT_MAX 0x0FFF
#define BT_GATT_EVT_START 0x1000
#define BT_GATT_EVT_MAX 0x1FFF
#define BT_AV_EVT_START 0x2000
#define BT_AV_EVT_MAX 0x2FFF
#define BT_AVRCP_EVT_START 0x3000
#define BT_AVRCP_EVT_MAX 0x3FFF
#define BT_HFP_EVT_START 0x4000
#define BT_HFP_EVT_MAX 0x4FFF
#define BT_HFAG_EVT_START 0x5000
#define BT_HFAG_EVT_MAX 0x5FFF

enum decode_type {
   PROTO_ENC_DEC,
   PROTO_RAW_BYTES,
   PROTO_NONE,
};

#define MAX_LENGTH_WITH_PROTO_NONE 6
// Keep adding all profiles matching range
#define PAYLOAD_LENGTH_WITH_PROTO_NONE 0

enum bluetooth_dm {
	BT_DM_ENABLE = BT_DM_EVT_START, /*enable*/
	BT_DM_DISABLE,
	BT_DM_CLEANUP,
	BT_DM_GET_ADAPTER_PROPERTIES,
	BT_DM_GET_ADAPTER_PROPERTY,
	BT_DM_GET_ADAPTER_PROPERTY_NAME,
	BT_DM_SET_ADAPTER_PROPERTY,
	BT_DM_GET_REMOTE_DEVICE_PROPERTIES,
	BT_DM_GET_REMOTE_DEVICE_PROPERTY_BY_TYPE,
	BT_DM_SET_REMOTE_DEVICE_PROPERTIES,
	BT_DM_GET_REMOTE_SRV_RECORD,
	BT_DM_GET_REMOTE_SERVICES,
	BT_DM_START_DISCOVERY,
	BT_DM_CANCEL_DISCOVERY,
	BT_DM_CREATE_BOND,
	BT_DM_CREATE_BOND_OOB,
	BT_DM_REMOVE_BOND,
	BT_DM_CANCEL_BOND,
	BT_DM_GET_CONNECTION_STATE,
	BT_DM_PIN_REPLY,
	BT_DM_SSP_REPLY,
	BT_DM_ADAPTER_STATE_CHANGE_CB,
	BT_DM_ADAPTER_PROPERTIES_CB,
	BT_DM_REMOTE_DEVICE_PROPERTIES_CB,
	BT_DM_DISCOVERY_STATE_CHANGE_CB,
	BT_DM_DEVICE_FOUND_CB,
	BT_DM_PIN_REQUEST_CB,
	BT_DM_SSP_REQUEST_CB,
	BT_DM_BOND_STATE_CHANGE_CB,
	BT_DM_ACL_STATE_CHANGE_CB,
	BT_DM_LE_ADAPTER_PROPERTIES_CB,
  BT_DM_SSR_CB,


	BT_DM_API_MAX = BT_DM_EVT_MAX,
};

enum bluetooth_rfcomm {
	BT_RFCOMM_CREATE_SOCKET = BT_RFCOMM_EVT_START, /*enable*/
	BT_RFCOMM_CONNECT_SOCKET,
	BT_RFCOMM_WRITE_SOCKET_DATA,
	BT_RFCOMM_SCN_CB,
	BT_RFCOMM_SRV_OPEN_CB,
	BT_RFCOMM_CLIENT_CONNECT_CB,
	BT_RFCOMM_SOCKET_DATA_CB,
    BT_RFCOMM_DISCONNECT_SOCKET,
	BT_RFCOMM_DISCONNECT_SOCKET_CB,
	BT_RFCOMM_CLOSE_SERVER,

	BT_RFCOMM_API_MAX = BT_RFCOMM_EVT_MAX,
};

enum bluetooth_sdp {
        BT_SDP_SEARCH = BT_SDP_EVT_START,
        BT_SDP_SEARCH_COMPLETE_CB,

        BT_SDP_API_MAX = BT_SDP_EVT_MAX,
};
